import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const primaryFont = Inter({
  subsets: ['latin'],
  weight: ['200', '500', '800']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={primaryFont.className}>{children}</body>
    </html>
  )
}
